### ISSUE TITLE
Link to share tutorial on twitter does not append url

### ISSUE THREAD

**Issue by MedAdrian** [stackbuilders/tutorials#102]
## Steps to reproduce
- Go to any tutorial article
- Click on the share to Twitter link
- The URL to the tutorial is not appended.

![image](https://user-images.githubusercontent.com/13720528/63181344-669e3000-c015-11e9-822f-43bf55e0afed.png)

## Expected
After clicking on the share to Twitter link, the user should be allowed to share the tutorial with the url.
![image](https://user-images.githubusercontent.com/13720528/63182042-2e97ec80-c017-11e9-917e-fa143767c4d1.png)

We may also include metadata for a preview on the tutorial as an image (like facebook does.

**Comment by Jagl257** [comment]
@MedAdrian, @h-garcia  Issue in staging ready for you guys to check it out.
