### ISSUE TITLE
Transformers requirement

### ISSUE THREAD

**Issue by tnrn9b** [stackbuilders/tutorials#74]
This line from the calc.cabal tutorial
`transformers     >= 0.3 && < 0.5`
requires the transformers package to be earlier than 0.5. Is this absolutely necessary?

**Comment by tnrn9b** [comment]
I'm going to close this. I just decided to use the stack install calc.

**Comment by juanpaucar** [comment]
Thanks for the heads up, we'll check it. I just checked the changelog and no breaking changes seem to be added on 0.5 an above

**Comment by tnrn9b** [comment]
That’s an awesomely fast reply!

"Juan Paucar" <notifications@github.com<mailto:notifications@github.com>> 3/2/18, 11:23 AM:


Thanks for the heads up, we'll check it. I just checked the changelog and no breaking changes seems to be added on 0.5 an above
