### ISSUE TITLE
Link to share tutorial on Facebook is broken

### ISSUE THREAD

**Issue by h-garcia** [stackbuilders/tutorials#94]
## Steps to reproduce
- Go to any tutorial article
- Click on the share to Facebook link
- There is an error that reads `href should represent a valid URL`

https://drive.google.com/file/d/1jCQTOkEDPVzvJBYW4qUkoi4eqibkm4Lp/view?usp=sharing

## Expected
After clicking on the share to facebook link, the user should be allowed to share the tutorial.

**Comment by Jagl257** [comment]
@h-garcia Issue in staging ready for you to check it out.
