### ISSUE TITLE
Adjust text at the end of tutorials 

### ISSUE THREAD

**Issue by h-garcia** [stackbuilders/tutorials#96]
As a marketing coordinator, I want the end line of the tutorials to be updated so that it doesn't reflect the Disqus integration that we previously had.

**Acceptance Criteria**
- Update the end line text of all tutorial posts. The link on the word Github should remain as is. 
- The word Twitter should be a hyperlink to https://twitter.com/stackbuilders
- The word facebook should be a hyperlink to https://www.facebook.com/StackBuildersEcuador/

*Current*
Thanks for reading this tutorial! If you have any feedback, please join the discussion below, or open issues and pull requests on GitHub.

*New*
Thanks for reading this tutorial! If you have any feedback, please feel free to drop us a line on Twitter or Facebook. You could also open issues and pull requests on GitHub.

**Comment by h-garcia** [comment]
@Jagl257 We are missing a `.` after the word Facebook. 
![image](https://user-images.githubusercontent.com/28160329/64825573-61d08b80-d583-11e9-840d-37df748a48b1.png)

**Comment by Jagl257** [comment]
@h-garcia I added the``` . ``` at the end of Facebook . I can merge it when you approved this [PR](https://github.com/stackbuilders/tutorials/pull/106). Thanks
